"""Tests for ingestion.extract: md/txt/docx built in-test, pdf via a stubbed PdfReader."""

from pathlib import Path

import pytest
from docx import Document  # pyright: ignore[reportMissingTypeStubs]

from sovereign_rag.errors import ExtractionError
from sovereign_rag.ingestion import extract as extract_module
from sovereign_rag.ingestion.extract import Fragment, extract

# --- markdown ---


def test_md_sections_follow_heading_stack() -> None:
    data = (
        b"Intro paragraph before any heading.\n"
        b"\n"
        b"# Setup\n"
        b"Install the tools.\n"
        b"\n"
        b"## Docker\n"
        b"Run compose up.\n"
        b"\n"
        b"# Usage\n"
        b"Ask a question.\n"
    )
    doc = extract(data, "md")
    assert [f.section for f in doc.fragments] == [None, "Setup", "Setup > Docker", "Usage"]
    assert doc.fragments[0].text == "Intro paragraph before any heading."
    assert doc.fragments[2].text == "Run compose up."
    assert all(f.page is None for f in doc.fragments)
    assert doc.meta == {}


# --- txt ---


def test_txt_utf8() -> None:
    doc = extract("héllo wörld".encode(), "txt")
    assert doc.fragments == [Fragment(text="héllo wörld")]
    assert doc.meta == {}


def test_txt_latin1_fallback() -> None:
    data = "café crème".encode("latin-1")  # invalid utf-8 on purpose
    doc = extract(data, "txt")
    assert doc.fragments[0].text == "café crème"


# --- docx (real file generated by python-docx) ---


def test_docx_headings_tables_and_meta(tmp_path: Path) -> None:
    document = Document()
    document.core_properties.title = "Demo doc"
    document.core_properties.author = "Alice"
    document.add_heading("Setup", level=1)
    document.add_paragraph("Install everything.")
    document.add_heading("Docker", level=2)
    document.add_paragraph("Run compose up.")
    table = document.add_table(rows=2, cols=2)
    table.cell(0, 0).text = "key"
    table.cell(0, 1).text = "value"
    table.cell(1, 0).text = "port"
    table.cell(1, 1).text = "8000"
    document.add_heading("Usage", level=1)
    document.add_paragraph("Ask a question.")
    path = tmp_path / "sample.docx"
    document.save(str(path))

    doc = extract(path.read_bytes(), "docx")

    sections = {f.text: f.section for f in doc.fragments}
    assert sections["Install everything."] == "Setup"
    assert sections["Run compose up."] == "Setup > Docker"
    assert sections["key | value\nport | 8000"] == "Setup > Docker"
    assert sections["Ask a question."] == "Usage"
    assert doc.meta == {"title": "Demo doc", "author": "Alice"}


# --- pdf (pypdf stubbed: no binary PDF fixtures in the repo) ---


class _StubPage:
    def __init__(self, text: str) -> None:
        self._text = text

    def extract_text(self) -> str:
        return self._text


class _StubInfo:
    title = "Compliance overview"
    author = "FDPIC"


def _stub_reader(pages: list[str], info: object | None) -> type[object]:
    class _StubReader:
        def __init__(self, stream: object) -> None:
            self.pages = [_StubPage(text) for text in pages]
            self.metadata = info

    return _StubReader


def test_pdf_pages_one_based_blank_skipped_and_meta(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(
        extract_module,
        "PdfReader",
        _stub_reader(["First page text.", "   \n  ", "Third page text."], _StubInfo()),
    )
    doc = extract(b"%PDF-stub", "pdf")
    assert [(f.text, f.page) for f in doc.fragments] == [
        ("First page text.", 1),
        ("Third page text.", 3),
    ]
    assert doc.meta == {"title": "Compliance overview", "author": "FDPIC"}


def test_pdf_without_metadata_has_empty_meta(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(
        extract_module, "PdfReader", _stub_reader(["Some real page content."], None)
    )
    doc = extract(b"%PDF-stub", "pdf")
    assert doc.meta == {}


def test_pdf_without_text_raises_extraction_error(monkeypatch: pytest.MonkeyPatch) -> None:
    monkeypatch.setattr(extract_module, "PdfReader", _stub_reader(["  ", ""], None))
    with pytest.raises(ExtractionError) as excinfo:
        extract(b"%PDF-stub", "pdf")
    assert (
        str(excinfo.value) == "no extractable text (scanned PDF? OCR is out of scope, see README)"
    )


# --- dispatch ---


def test_unsupported_content_type_raises() -> None:
    with pytest.raises(ExtractionError):
        extract(b"whatever", "exe")
